data-path="./data"
data-storage-format="FOREST"
genesis-file="../genesis.json" 
bootnodes=[]
rpc-http-enabled=true 
rpc-http-api=["ADMIN","ETH","NET","PERM","QBFT"] 
rpc-http-host="0.0.0.0"
host-allowlist=["*"] 
rpc-http-cors-origins=["all"] 
rpc-http-port="8545" 
p2p-port="30303" 
profile="ENTERPRISE"
# permissions-nodes-contract-enabled=true
# permissions-nodes-contract-address="0x0000000000000000000000000000000000009999"
# permissions-nodes-contract-version=2
#permissions-nodes-config-file-enabled=true