data-path="./data"
data-storage-format="FOREST"
genesis-file="../genesis.json" 
bootnodes=[]
rpc-http-enabled=true 
rpc-http-api=["ETH","NET","QBFT"] 
host-allowlist=["*"] 
rpc-http-cors-origins=["all"] 
rpc-http-port="8545" 
p2p-port="30303" 
profile="ENTERPRISE"
# miner-enabled=true
# miner-coinbase="0x02A82bE03b5a4A38258bF176e99551d2afe7e452"